version: '3.4'

services:
  testvuewebapp:
    image: rgrty-testvuewebapp
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rgrty-testvuewebapp
    environment:
      MS_SQL_DB: "Data Source=192.168.50.7;Initial Catalog=Billing;User Id=DB_USER;Password=jlbyldfnhb"
    ports:
      - 5600:5600
