version: '3.4'

services:
  testvuewebapp:
    image: rgrty-testvuewebapp
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rgrty-testvuewebapp
    environment:
      MS_SQL_DB: Data Source=192.168.51.11;Initial Catalog=Billing;User Id=UserAlpha;Password=ALSUtCF%utnWJk6Oa~RI?#q0v!
    ports:
      - 5600:5600
